In [6]:
import numpy as np

# 
Numpy is Numerical Python.

In [37]:
aaray1 = np.array([[5,6,7],[1,2,3]])

In [38]:
aaray1

array([[5, 6, 7],
       [1, 2, 3]])

In [42]:
array1 = np.zeros([5,6] , dtype=int) 

In [43]:
dtype = array1

In [44]:
print(dtype)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [49]:
array4 = np.arange(23,50,8)

In [50]:
array4

array([23, 31, 39, 47])

# Linspace

In [51]:

array3 = np.linspace(16,10,55)

In [52]:
array3

array([16.        , 15.88888889, 15.77777778, 15.66666667, 15.55555556,
       15.44444444, 15.33333333, 15.22222222, 15.11111111, 15.        ,
       14.88888889, 14.77777778, 14.66666667, 14.55555556, 14.44444444,
       14.33333333, 14.22222222, 14.11111111, 14.        , 13.88888889,
       13.77777778, 13.66666667, 13.55555556, 13.44444444, 13.33333333,
       13.22222222, 13.11111111, 13.        , 12.88888889, 12.77777778,
       12.66666667, 12.55555556, 12.44444444, 12.33333333, 12.22222222,
       12.11111111, 12.        , 11.88888889, 11.77777778, 11.66666667,
       11.55555556, 11.44444444, 11.33333333, 11.22222222, 11.11111111,
       11.        , 10.88888889, 10.77777778, 10.66666667, 10.55555556,
       10.44444444, 10.33333333, 10.22222222, 10.11111111, 10.        ])

In [53]:

array4 = np.full([11,8,1],6)

In [55]:
array4

array([[[6],
        [6],
        [6],
        [6],
        [6],
        [6],
        [6],
        [6]],

       [[6],
        [6],
        [6],
        [6],
        [6],
        [6],
        [6],
        [6]],

       [[6],
        [6],
        [6],
        [6],
        [6],
        [6],
        [6],
        [6]],

       [[6],
        [6],
        [6],
        [6],
        [6],
        [6],
        [6],
        [6]],

       [[6],
        [6],
        [6],
        [6],
        [6],
        [6],
        [6],
        [6]],

       [[6],
        [6],
        [6],
        [6],
        [6],
        [6],
        [6],
        [6]],

       [[6],
        [6],
        [6],
        [6],
        [6],
        [6],
        [6],
        [6]],

       [[6],
        [6],
        [6],
        [6],
        [6],
        [6],
        [6],
        [6]],

       [[6],
        [6],
        [6],
        [6],
        [6],
        [6],
        [6],
        [6]],

       [[6],
        [6],
        [6],
       

In [56]:

array8 = np.identity(10)

In [57]:
array8

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# Converting list

In [59]:

list_ = [8,7,5]
array7 = np.asarray(list_)

In [60]:
array7

array([8, 7, 5])

In [64]:
g = np.random.randint(5,8,[5,4])

In [65]:
g

array([[7, 5, 6, 5],
       [5, 7, 7, 7],
       [5, 7, 5, 7],
       [6, 5, 5, 5],
       [7, 5, 6, 6]])

In [80]:

c = np.random.randint(5,10,(2,7))

In [81]:
c

array([[5, 8, 7, 7, 9, 8, 8],
       [6, 9, 9, 9, 9, 8, 9]])

In [83]:

g = np.random.rand(5, 4)
c = np.random.rand(5, 4) 

In [84]:
r = np.multiply(g, c)

In [85]:
print(r)

[[0.10651825 0.0997088  0.31331816 0.55271927]
 [0.01716385 0.23772302 0.17104524 0.099693  ]
 [0.27519779 0.19287096 0.64389899 0.11138547]
 [0.20186504 0.47767592 0.00704228 0.04260863]
 [0.17804374 0.06258435 0.18254381 0.35842019]]


In [86]:

n = np.divide(g,c)

In [87]:
n

array([[ 0.42637366,  0.11154803,  0.48944049,  0.56547552],
       [28.46258545,  0.35274168,  0.25052553,  0.20451651],
       [ 0.49506746,  1.79714718,  1.13015261,  3.36799701],
       [ 1.78895457,  0.85689191,  0.17121123, 15.73820445],
       [ 1.04184652,  0.35003677,  1.61157341,  0.66878394]])

In [88]:
h = np.divide(20,9)


In [89]:
h

2.2222222222222223

In [90]:
multiply = np.multiply(23,52)

In [91]:
print(multiply)

1196


In [94]:


x= np.random.randint(2,12,[2,4])

In [95]:
x

array([[11, 10,  2,  2],
       [ 2,  7,  5, 10]])

# Aggrigation

In [104]:

d = np.random.randint(2,13,[3,4])
print(d)


[[ 2  6  9  9]
 [ 4 12  3  9]
 [ 3  6  8  5]]


In [105]:
total_sum = np.sum(d)

In [106]:
print(total_sum)

76


In [107]:
print(np.sum(d))

76


In [108]:
print(d)

[[ 2  6  9  9]
 [ 4 12  3  9]
 [ 3  6  8  5]]


In [109]:
maximum = d.max()

In [111]:
print(maximum)

12


In [112]:
d.sum()

76

# Transpose

In [115]:
array5= np.random.randint(3,15,[5,7])

transpose = np.transpose(array5)


In [116]:
print(array5)

[[12  3 14  7  9 10  4]
 [13  4 14  3 12 12  8]
 [13  5 11  8  5  5 14]
 [14  9 10  7  7 10 12]
 [11  7 14 13 14  3 13]]


In [117]:
print(transpose)

[[12 13 13 14 11]
 [ 3  4  5  9  7]
 [14 14 11 10 14]
 [ 7  3  8  7 13]
 [ 9 12  5  7 14]
 [10 12  5 10  3]
 [ 4  8 14 12 13]]
